config/routes.rb
Rails.application.routes.draw do
  scope '/api' do
    resources :session_scores
    resources :session_players
    resources :session_categories
    resources :sessions do
      get 'winner', on: :member
      resource :session_shares, only: [:create]
    end
    resources :categories
    resources :games
    resources :players
    resource :user, only: [:show]
    devise_for :users,
      controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  end
  root 'homepage#index'
  get '/*path' => 'homepage#index'
end

app/models/session_score.rb
class SessionScore < ApplicationRecord
    belongs_to :session
    belongs_to :session_category
    belongs_to :session_player
end

app/controllers/session_scores_controller.rb
class SessionScoresController < ApplicationController
  before_action :set_session_score, only: %i[ show edit update destroy ]

  # GET /session_scores or /session_scores.json
  def index
    @session_scores = SessionScore.includes(:session_category, :session_player)
  end

  # GET /session_scores/1 or /session_scores/1.json
  def show 
  end

  # GET /session_scores/new
  def new
    @session_score = SessionScore.new
  end

  # GET /session_scores/1/edit
  def edit
  end

  # POST /session_scores or /session_scores.json
  def create
    @session_score = SessionScore.new(session_score_params)

    if @session_score.save
      render json: @session_score
    else
      render json: @session_score.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /session_scores/1 or /session_scores/1.json
  def update
     if @session_score.update(session_score_params)
      render json: @session_score
     else 
      render json: @session_score.errors, status: :unprocessable_entity
     end
  end

  # DELETE /session_scores/1 or /session_scores/1.json
  def destroy
    @session_score.destroy
    render json: {message: 'okay'}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session_score
      @session_score = SessionScore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def session_score_params
      params.require(:session_score).permit(:amount, :session_category_id, :session_player_id, :session_id, :win)
    end
end

app/helpers/session_scores_helper.rb
module SessionScoresHelper
end

app/views/session_scores/_form.html.erb
<%= form_with(model: session_score) do |form| %>
  <% if session_score.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(session_score.errors.count, "error") %> prohibited this session_score from being saved:</h2>

      <ul>
        <% session_score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/session_scores/_session_score.html.erb
<div id="<%= dom_id session_score %>">
  <p>
    <strong>Amount:</strong>
    <%= session_score.amount %>
  </p>

</div>

app/views/session_scores/edit.html.erb
<h1>Editing session score</h1>

<%= render "form", session_score: @session_score %>

<br>

<div>
  <%= link_to "Show this session score", @session_score %> |
  <%= link_to "Back to session scores", session_scores_path %>
</div>

app/views/session_scores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Session scores</h1>

<div id="session_scores">
  <% @session_scores.each do |session_score| %>
    <%= render session_score %>
    <p>
      <%= link_to "Show this session score", session_score %>
    </p>
  <% end %>
</div>

<%= link_to "New session score", new_session_score_path %>

app/views/session_scores/new.html.erb
<h1>New session score</h1>

<%= render "form", session_score: @session_score %>

<br>

<div>
  <%= link_to "Back to session scores", session_scores_path %>
</div>

app/views/session_scores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @session_score %>

<div>
  <%= link_to "Edit this session score", edit_session_score_path(@session_score) %> |
  <%= link_to "Back to session scores", session_scores_path %>

  <%= button_to "Destroy this session score", @session_score, method: :delete %>
</div>