config/routes.rb
Rails.application.routes.draw do
  scope '/api' do
    resources :session_scores
    resources :session_players
    resources :session_categories
    resources :sessions do
      get 'winner', on: :member
      resource :session_shares, only: [:create]
    end
    resources :categories
    resources :games
    resources :players
    resource :user, only: [:show]
    devise_for :users,
      controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  end
  root 'homepage#index'
  get '/*path' => 'homepage#index'
end

app/models/session_player.rb
class SessionPlayer < ApplicationRecord
    belongs_to :session
    has_many :session_scores, -> { order(id: :asc) }, dependent: :destroy

    after_create :create_scores
    
    def total_score
        self.session_scores.map(&:amount).sum
    end

    def winning_categories
        self.session_scores.where(win: true).map{|t| t.session_category.name}
    end

    private

    def create_scores
        self.session.session_categories.each do |c|
            self.session_scores.create(amount: 0, session_id: self.session.id, session_category_id: c.id, win: c.win)
        end
    end


end

app/controllers/session_players_controller.rb
class SessionPlayersController < ApplicationController
  before_action :set_session_player, only: %i[ show edit update destroy ]

  # GET /session_players or /session_players.json
  def index
    @session_players = SessionPlayer.all
  end

  # GET /session_players/1 or /session_players/1.json
  def show
  end

  # GET /session_players/new
  def new
    @session_player = SessionPlayer.new
  end

  # GET /session_players/1/edit
  def edit
  end

  # POST /session_players or /session_players.json
  def create
    @session_player = SessionPlayer.new(session_player_params)

      if @session_player.save!
        render json: @session_player
      else
        render json: @session_player.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /session_players/1 or /session_players/1.json
  def update
    if @session_player.update(session_player_params)
      render json: @session_player
    else
      render json: @session_player.errors, status: :unprocessable_entity
    end
  end

  # DELETE /session_players/1 or /session_players/1.json
  def destroy
    @session_player.destroy

    render json: {message: 'okay'}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session_player
      @session_player = SessionPlayer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def session_player_params
      params.require(:session_player).permit(:name, :session_id)
    end
end

app/helpers/session_players_helper.rb
module SessionPlayersHelper
end

app/views/session_players/_form.html.erb
<%= form_with(model: session_player) do |form| %>
  <% if session_player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(session_player.errors.count, "error") %> prohibited this session_player from being saved:</h2>

      <ul>
        <% session_player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/session_players/_session_player.html.erb
<div id="<%= dom_id session_player %>">
  <p>
    <strong>Name:</strong>
    <%= session_player.name %>
  </p>

</div>

app/views/session_players/edit.html.erb
<h1>Editing session player</h1>

<%= render "form", session_player: @session_player %>

<br>

<div>
  <%= link_to "Show this session player", @session_player %> |
  <%= link_to "Back to session players", session_players_path %>
</div>

app/views/session_players/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Session players</h1>

<div id="session_players">
  <% @session_players.each do |session_player| %>
    <%= render session_player %>
    <p>
      <%= link_to "Show this session player", session_player %>
    </p>
  <% end %>
</div>

<%= link_to "New session player", new_session_player_path %>

app/views/session_players/new.html.erb
<h1>New session player</h1>

<%= render "form", session_player: @session_player %>

<br>

<div>
  <%= link_to "Back to session players", session_players_path %>
</div>

app/views/session_players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @session_player %>

<div>
  <%= link_to "Edit this session player", edit_session_player_path(@session_player) %> |
  <%= link_to "Back to session players", session_players_path %>

  <%= button_to "Destroy this session player", @session_player, method: :delete %>
</div>